# Generated by Django 3.2 on 2026-02-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20260224_1335'),
        ('billing', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='consultations.prescription'),
        ),
    ]
