# Generated by Django 3.2 on 2026-02-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20260224_1335'),
        ('billing', '0003_alter_invoice_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='consultations.prescriptionitem'),
        ),
    ]
