# Generated by Django 3.2 on 2026-02-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceitem_prescription_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
