# Generated by Django 3.2 on 2026-02-26 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_batch'),
        ('billing', '0006_invoicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='pharmacy.batch')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='billing.invoiceitem')),
            ],
        ),
    ]
