# Generated by Django 3.2 on 2026-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_invoiceitembatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
