# Generated by Django 3.2 on 2026-02-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
    ]
