# Generated by Django 3.2 on 2026-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_medicine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total GST percentage (will be split into CGST + SGST)', max_digits=5),
        ),
    ]
