# Generated by Django 3.2 on 2026-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260218_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
