# Generated by Django 3.2 on 2026-03-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='DiagnosisMaster',
        ),
    ]
